train:
  epochs: 1000
  batch_size: 4
  lr: 0.0001
  val_percent: 0.01
  weight_decay: 0.000000001
  momentum: 0.999
  amp: False
  device: 'cuda:0'
  gradient_clipping: 0.1
  save_checkpoint: True
  img_scale: 0.1
  dir_checkpoint: './checkpoint'
  image_size: [540, 960]
  num_work: 0
  

Unet:
  n_channels: 3
  n_classes: 1
  bilinear: False
  hiden_channels: [32, 64, 128, 256]
